import time
import mraa
e=mraa.Gpio(36)
e.dir(mraa.DIR_OUT)
e.write(1)
f=mraa.Gpio(48)
f.dir(mraa.DIR_OUT)
f.write(1)
g=mraa.Gpio(47)
g.dir(mraa.DIR_OUT)
g.write(1)
h=mraa.Gpio(32)
h.dir(mraa.DIR_OUT)
h.write(1)
i=mraa.Gpio(46)
i.dir(mraa.DIR_OUT)
i.write(1)
while True:
	h.write(0)
	time.sleep(2)
	h.write(1)
	time.sleep(2)
